openapi: 3.0.1
info:
  title: API Personas
  version: 1.0.0

paths:
  /personas:
    get:
      summary: Listado de personas
      tags: [Personas]
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Persona'

    post:
      summary: Crear persona
      tags: [Personas]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PersonaInput'
      responses:
        '201':
          description: Persona creada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Persona'
        '400':
          description: Error de validación
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorValidacion'
    delete:
      summary: Eliminar todas las personas
      tags: [Personas]
      responses:
        '200':
          description: Personas eliminadas
          content:
            application/json:
              schema:
                type: boolean
        '404':
          description: No había personas que borrar
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorNotFound'
  /personas/{id}:
    get:
      summary: Obtener persona por ID
      tags: [Personas]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Persona'
        '404':
          description: Persona no encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorNotFound'

    put:
      summary: Actualizar persona
      tags: [Personas]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PersonaInput'
      responses:
        '200':
          description: Persona actualizada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Persona'
        '400':
          description: Error de validación
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorValidacion'
        '404':
          description: Persona no encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorNotFound'

    delete:
      summary: Eliminar persona
      tags: [Personas]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Persona eliminada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Persona'
        '404':
          description: Persona no encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorNotFound'


components:
  schemas:
    Persona:
      type: object
      required: [id, nombre]
      properties:
        id:
          type: integer
        nombre:
          type: string
        edad:
          type: integer

    PersonaInput:
      type: object
      required: [nombre]
      properties:
        nombre:
          type: string
        edad:
          type: integer

    ErrorNotFound:
      type: object
      properties:
        mensaje:
          type: string

    ErrorValidacion:
      type: object
      properties:
        mensaje:
          type: string
