spring.application.name=curso1_spring1

# Configuracion de base de datos H2
spring.datasource.url=jdbc:h2:mem:curso1db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true

# Configuracion de H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Mostrar SQL en la consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
